pypi:
    image:
        name: pretix/ci-image
    script:
        - cat $PYPIRC > ~/.pypirc
        - pip install -U pip uv
        - uv pip install --system -U setuptools wheel twine
        - uv pip install --system -r requirements_dev.txt
        - python setup.py sdist develop
        - python setup.py sdist clean
        - python setup.py sdist
        - python setup.py bdist_wheel
        - twine check dist/*
        - twine check upload/*
    only:
        - pypi
    artifacts:
        paths:
            - dist/
