language: python
dist: xenial
sudo: false
install:
  - pip install tox
script:
  - tox
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django32-sqlite
    - python: 3.7
      env: TOXENV=py36-django32-sqlite
    - python: 3.7
      env: TOXENV=py37-django40-sqlite
    - python: 3.8
      env: TOXENV=py38-django32-sqlite
    - python: 3.9
      env: TOXENV=py39-django40-sqlite
    - python: 3.10
      env: TOXENV=py310-django32-sqlite
    - python: 3.10
      env: TOXENV=py310-django40-sqlite
    - python: 3.10
      env: TOXENV=coverage
    - python: 3.10
      env: TOXENV=doctest
    - python: 3.10
      env: TOXENV=style
